sonar.projectKey=SarahiMalpica_nailflow-inventario
sonar.organization=sarahimalpica
sonar.projectName=nailflow-inventario

sonar.sources=src,public,server.js
sonar.tests=tests
sonar.test.inclusions=tests/**/*.test.js

sonar.exclusions=**/node_modules/**,data/**,evidencias-del-proyecto/**
sonar.coverage.exclusions=public/**,server.js

sonar.javascript.lcov.reportPaths=evidencias-del-proyecto/cobertura/lcov.info
sonar.sourceEncoding=UTF-8
